name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "26.1-v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acae303f78787760001b19b39dcde9972ab454a2c8b531c043760f36063c20d8"

[versions]
fabric = "0.18.6"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
