name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.19.3-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b018be85a2c7dbfd4f4390940db06f4d3724cd76ce9366c68eb3d07ef7904acb"

[versions]
minecraft = "1.19.3"
quilt = "0.17.10"

[options]
acceptable-game-versions = ["1.19.2", "1.19.3"]
