name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.21.8-v3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9785cb15432453ce825e37ddab92774cae74ec8ebf08bcf19d00c5dc9a178eed"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
