name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.21.4-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aca11c7625c68fb6bccd4f70c5b03546a90de69dd0009ba074a2ac61da72ccb7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
