name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "26.1-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9de5f941d4e705e01b6e79faadea0da2a9b1fcf47332cff8fe2b98a98c88666"

[versions]
fabric = "0.18.6"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
