name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.20.1-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc0db34d4e5d58f8f832a0717babb179b9fc183a65f3d7a9e19f1c2ffe4fc816"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
