name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.21.8-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c83d7ba6edce74e0f76ddf91ce1e32071044d28fe23398d8f5b43505e29cb3f6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
