name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.19-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81b4edeb55a078d3aede5721f01f4648573404a8dc49f628e00ecd3889194579"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
