name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.21.11-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b25715412a13adeaa8ae590a13e494e4a59f8322cdb0a5bd914f94320c7838"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
