name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.19-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8406a1323cbbfbb5119805cb3cc926d41cbf3d7a462cdda606de97b92f210627"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
