name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.21.9-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24fc6ee0b2703bc242ba26c1c9f5b6e8b2de54d528dca6c64a68785ecb6d77d1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"

[options]
acceptable-game-versions = ["1.21.9"]
