name = "A Sprinkle of Enhancements"
author = "xIGBClutchIx"
version = "1.21-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3e9d538a4c19537b889163a06d7581d6ff9b96a69170d2954b94c7ebcd1b17a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
